apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: web-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: veenayak/simple_3_tier_app-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "database"

            - name: DATABASE_NAME
              value: "tododb"

            - name: DATABASE_USER
              value: "todo_user"

            - name: DATABASE_PASSWORD
              value: "todo_pass"

            - name: DATABASE_PORT
              value: "5432"
