apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: project-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
        - name: project-backend
          image: veenayak/devsecops_cdacproject-backend:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always