apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: project-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
        - name: project-frontend
          image: veenayak/devsecops_cdacproject-frontend:latest
          ports:
            - containerPort: 5173
          imagePullPolicy: Always