apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: web-app
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tododb"
            - name: POSTGRES_USER
              value: "todo_user"
            - name: POSTGRES_PASSWORD
              value: "todo_pass"
