apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: simple_3_tier_app-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
